apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
  name: snoxr11
  namespace: snoxr11
spec:
  clusters:
    - clusterName: snoxr11
      networkType: "OVNKubernetes"
      extraManifests:
        searchPaths:
          - extra-manifest-xr11-32c-sno-414/
        filter:
          inclusionDefault: exclude
          include:
            - du-sno-mc.yaml
            - 99-sync-time-once-master.yaml
      installConfigOverrides: "{\"capabilities\":{\"baselineCapabilitySet\": \"None\", \"additionalEnabledCapabilities\": [ \"marketplace\", \"NodeTuning\", \"Console\" ] }}"
      clusterLabels:
        common: true
        sites: snoxr11
        clustertype: sno
      clusterNetwork:
        - cidr: fd02::/48
          hostPrefix: 64
      serviceNetwork:
        - fd03::/112
      machineNetwork:
        - cidr: 2605:ca40:3:9::/64
      additionalNTPSources:
        - mba-master0.mbabs.mavdallab.com
        - mba-master1.mbabs.mavdallab.com
        - mba-master2.mbabs.mavdallab.com
