apiVersion: k8s.ovn.org/v1
kind: EgressFirewall
metadata:
labels:
    env: default
  name: default
  namespace: openshift-gitops
spec:
  egress:
    - to:
        cidrSelector: 0.0.0.0/0
      type: Deny
