apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default
namePrefix: nobel-ms-
nameSuffix: -dev

resources:
  - EgressFirewall.yaml

patches:
- target:
    kind: EgressFirewall
    name: nobel-ms-default-dev
  options:
    allowNameChange: true
  patch: |-
      - op: replace
        path: /metadata/name
        value: default
      - op: replace
        path: /metadata/labels/env
        value: replace
