apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - EgressFirewall.yam

patches:
  - target:
      kind: EgressFirewall
    patch: |
      - op: add
        path: /metadata/labels
        value: {"forceName": "default"}


replacements:
- source:
    group: k8s.ovn.org
    version: v1
    kind: EgressFirewall
    fieldPath: metadata.labels.forceName
  targets:
  - select:
      group: k8s.ovn.org
      version: v1
      kind: EgressFirewall
    fieldPaths:
    - metadata.name


namespace: openshift-gitops
namePrefix: nobel-ms-
nameSuffix: -dev
